/**
 * Auto-generated by infra/scripts/deploy.ts
 * Do not edit manually.
 */

export const deployedAddresses = {
  chainId: 31337,
  StealthMetaAddressRegistry: "0x5095d3313C76E8d29163e40a0223A5816a8037D8" as const,
  StealthAddressAnnouncer: "0x391342f5acAcaaC9DE1dC4eC3E03f2678f7c78F1" as const,
  USDC: "0x6d925938Edb8A16B3035A4cF34FAA090f490202a" as const,
  USDT: "0xED8CAB8a931A4C0489ad3E3FB5BdEA84f74fD23E" as const,
} as const;

export type DeployedAddresses = typeof deployedAddresses;
