/**
 * Deploy the Groth16Verifier and OpaqueReputationVerifier contracts.
 * Writes addresses to frontend config so the UI can submit proofs.
 *
 * Run:
 *   cd infra && npx hardhat compile && tsx scripts/deploy-reputation.ts
 *
 * Env vars (from .env):
 *   SEPOLIA_RPC_URL, SEPOLIA_PRIVATE_KEY  — for Sepolia deployment
 *   DEPLOYER_ADDRESS                      — admin address for the verifier (defaults to deployer)
 */

import { ethers } from "ethers";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import dotenv from "dotenv";

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ARTIFACTS_DIR = path.join(__dirname, "..", "artifacts", "contracts");
const FRONTEND_CONTRACTS = path.join(__dirname, "..", "..", "frontend", "src", "contracts");

type Artifact = { abi: unknown[]; bytecode?: string };

function loadArtifact(contractName: string): Artifact {
  const solName = `${contractName}.sol`;
  const p = path.join(ARTIFACTS_DIR, solName, `${contractName}.json`);
  const raw = fs.readFileSync(p, "utf-8");
  const artifact = JSON.parse(raw) as Artifact;
  if (!Array.isArray(artifact.abi)) throw new Error(`No ABI in ${p}`);
  return artifact;
}

async function main() {
  const rpcUrl = process.env.SEPOLIA_RPC_URL;
  if (!rpcUrl) throw new Error("Set SEPOLIA_RPC_URL in .env");

  const privateKey = process.env.SEPOLIA_PRIVATE_KEY;
  if (!privateKey?.startsWith("0x") || privateKey.length < 64) {
    throw new Error("Set SEPOLIA_PRIVATE_KEY in .env");
  }

  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const signer = new ethers.Wallet(privateKey, provider);
  const deployerAddress = await signer.getAddress();
  const chainId = Number((await provider.getNetwork()).chainId);
  let nextNonce = await signer.getNonce("latest");

  console.log(`Deploying reputation contracts on chain ${chainId}`);
  console.log(`Deployer: ${deployerAddress}`);
  console.log(`Nonce: ${nextNonce}\n`);

  // 1. Deploy Groth16Verifier
  console.log("Deploying Groth16Verifier...");
  const verifierArtifact = loadArtifact("Groth16Verifier");
  const verifierFactory = new ethers.ContractFactory(
    verifierArtifact.abi as ethers.InterfaceAbi,
    verifierArtifact.bytecode ?? "0x",
    signer
  );
  const verifierContract = await verifierFactory.deploy({ nonce: nextNonce });
  await verifierContract.waitForDeployment();
  const groth16Address = await verifierContract.getAddress();
  nextNonce += 1;
  console.log(`  Groth16Verifier deployed at: ${groth16Address}`);

  // 2. Deploy OpaqueReputationVerifier
  const adminAddress = process.env.DEPLOYER_ADDRESS ?? deployerAddress;
  console.log(`\nDeploying OpaqueReputationVerifier (admin: ${adminAddress})...`);
  const repArtifact = loadArtifact("OpaqueReputationVerifier");
  const repFactory = new ethers.ContractFactory(
    repArtifact.abi as ethers.InterfaceAbi,
    repArtifact.bytecode ?? "0x",
    signer
  );
  const repContract = await repFactory.deploy(groth16Address, adminAddress, { nonce: nextNonce });
  await repContract.waitForDeployment();
  const repAddress = await repContract.getAddress();
  nextNonce += 1;
  console.log(`  OpaqueReputationVerifier deployed at: ${repAddress}`);

  // 3. Write reputation addresses to frontend
  const reputationJson = {
    chainId,
    Groth16Verifier: groth16Address,
    OpaqueReputationVerifier: repAddress,
    admin: adminAddress,
  };

  fs.mkdirSync(FRONTEND_CONTRACTS, { recursive: true });

  const jsonPath = path.join(FRONTEND_CONTRACTS, "reputation-addresses.json");
  fs.writeFileSync(jsonPath, JSON.stringify(reputationJson, null, 2), "utf-8");
  console.log(`\nWrote ${jsonPath}`);

  const tsContent = `/**
 * Auto-generated by infra/scripts/deploy-reputation.ts
 * Do not edit manually.
 */

export const reputationAddresses = {
  chainId: ${chainId},
  Groth16Verifier: "${groth16Address}" as const,
  OpaqueReputationVerifier: "${repAddress}" as const,
  admin: "${adminAddress}" as const,
} as const;

export type ReputationAddresses = typeof reputationAddresses;
`;

  const tsPath = path.join(FRONTEND_CONTRACTS, "reputationAddresses.ts");
  fs.writeFileSync(tsPath, tsContent, "utf-8");
  console.log(`Wrote ${tsPath}`);

  // 4. Copy ABIs
  const abisDir = path.join(FRONTEND_CONTRACTS, "abis");
  fs.mkdirSync(abisDir, { recursive: true });

  for (const name of ["Groth16Verifier", "OpaqueReputationVerifier"]) {
    const artifact = loadArtifact(name);
    const abiPath = path.join(abisDir, `${name}.json`);
    fs.writeFileSync(abiPath, JSON.stringify(artifact.abi, null, 2), "utf-8");
    console.log(`Copied ABI: abis/${name}.json`);
  }

  console.log("\nDone! Summary:");
  console.log(`  Chain:                      ${chainId}`);
  console.log(`  Groth16Verifier:            ${groth16Address}`);
  console.log(`  OpaqueReputationVerifier:    ${repAddress}`);
  console.log(`  Admin:                      ${adminAddress}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
