/**
 * Hardhat deployment script using Ethers.js.
 * Deploys StealthMetaAddressRegistry and StealthAddressAnnouncer,
 * writes deployedAddresses.ts and copies ABIs to the frontend.
 *
 * Run: npx hardhat run scripts/deploy.ts --network localhost
 * (Start local node first: npx hardhat node)
 */

import { ethers } from "ethers";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const CONTRACTS = ["StealthMetaAddressRegistry", "StealthAddressAnnouncer"] as const;
const ARTIFACTS_DIR = path.join(__dirname, "..", "artifacts", "contracts");
const FRONTEND_ROOT = path.join(__dirname, "..", "..", "frontend");
const FRONTEND_CONTRACTS = path.join(FRONTEND_ROOT, "src", "contracts");
const FRONTEND_ABIS = path.join(FRONTEND_CONTRACTS, "abis");

function getArtifactPath(contractName: string): string {
  const solName = `${contractName}.sol`;
  return path.join(ARTIFACTS_DIR, solName, `${contractName}.json`);
}

type Artifact = { abi: unknown[]; bytecode?: string };

function loadArtifact(contractName: string): Artifact {
  const p = getArtifactPath(contractName);
  const raw = fs.readFileSync(p, "utf-8");
  const artifact = JSON.parse(raw) as Artifact;
  if (!Array.isArray(artifact.abi)) throw new Error(`No ABI in ${p}`);
  return artifact;
}

async function main() {
  const rpcUrl = process.env.RPC_URL ?? "http://127.0.0.1:8545";
  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const privateKey = "0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e";
  if (!privateKey) {
    throw new Error("Set PRIVATE_KEY (e.g. from Hardhat node account #0) to run deploy.");
  }
  const signer = new ethers.Wallet(privateKey, provider);
  const chainId = Number((await provider.getNetwork()).chainId);

  const addresses: Record<string, string> = {};
  let nextNonce = await signer.getNonce("latest");

  for (const contractName of CONTRACTS) {
    const artifact = loadArtifact(contractName);
    const factory = new ethers.ContractFactory(
      artifact.abi as ethers.InterfaceAbi,
      artifact.bytecode ?? "0x",
      signer
    );
    const contract = await factory.deploy({ nonce: nextNonce });
    await contract.waitForDeployment();
    nextNonce += 1;
    const address = await contract.getAddress();
    addresses[contractName] = address;
    console.log(`${contractName} deployed at ${address}`);
  }

  // Ensure frontend contract dirs exist
  fs.mkdirSync(FRONTEND_CONTRACTS, { recursive: true });
  fs.mkdirSync(FRONTEND_ABIS, { recursive: true });

  // Write deployedAddresses.ts
  const addressesContent = `/**
 * Auto-generated by infra/scripts/deploy.ts
 * Do not edit manually.
 */

export const deployedAddresses = {
  chainId: ${chainId},
  StealthMetaAddressRegistry: "${addresses.StealthMetaAddressRegistry}" as const,
  StealthAddressAnnouncer: "${addresses.StealthAddressAnnouncer}" as const,
} as const;

export type DeployedAddresses = typeof deployedAddresses;
`;

  fs.writeFileSync(
    path.join(FRONTEND_CONTRACTS, "deployedAddresses.ts"),
    addressesContent,
    "utf-8"
  );
  console.log("Wrote frontend/src/contracts/deployedAddresses.ts");

  // Copy ABIs (only the ABI array as JSON for smaller files)
  for (const contractName of CONTRACTS) {
    const artifact = loadArtifact(contractName);
    const abiPath = path.join(FRONTEND_ABIS, `${contractName}.json`);
    fs.writeFileSync(abiPath, JSON.stringify(artifact.abi, null, 2), "utf-8");
    console.log(`Copied ABI to frontend/src/contracts/abis/${contractName}.json`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
