// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.20;

/// @title MockGroth16Verifier
/// @notice Test-only mock that always returns true. Replace with the real
///         Groth16Verifier generated by `snarkjs zkey export solidityverifier`.
contract MockGroth16Verifier {
    function verifyProof(
        uint256[2] calldata,
        uint256[2][2] calldata,
        uint256[2] calldata,
        uint256[5] calldata
    ) external pure returns (bool) {
        return true;
    }
}
