// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.20;

/// @title OpaqueReputationVerifier
/// @notice On-chain verifier for Stealth Attestation ZK-SNARK proofs.
///         Accepts Groth16 proofs that a user owns a stealth address with a specific
///         attestation without revealing the address.
/// @dev Uses a nullifier registry to prevent Sybil attacks (same key + same action = same nullifier).
///      The Merkle root is validated against recent roots stored by the Stealth Registry.

interface IGroth16Verifier {
    function verifyProof(
        uint256[2] calldata pA,
        uint256[2][2] calldata pB,
        uint256[2] calldata pC,
        uint256[5] calldata pubSignals
    ) external view returns (bool);
}

contract OpaqueReputationVerifier {
    // =========================================================================
    // Errors
    // =========================================================================

    error InvalidProof();
    error NullifierAlreadyUsed();
    error InvalidMerkleRoot();
    error RootExpired();
    error ZeroAddress();

    // =========================================================================
    // Events
    // =========================================================================

    /// @notice Emitted when a reputation proof is successfully verified.
    event ReputationVerified(
        uint256 indexed attestationId,
        uint256 indexed nullifier,
        address indexed verifier,
        bytes32 merkleRoot
    );

    /// @notice Emitted when a new Merkle root is submitted.
    event MerkleRootUpdated(bytes32 indexed root, uint256 blockNumber);

    // =========================================================================
    // State
    // =========================================================================

    /// @notice The Groth16 verifier contract (generated by snarkjs).
    IGroth16Verifier public immutable groth16Verifier;

    /// @notice Admin address that can update Merkle roots.
    address public admin;

    /// @notice Registry of used nullifiers — prevents double-claims.
    mapping(uint256 => bool) public usedNullifiers;

    /// @notice Valid Merkle roots and their submission timestamps.
    mapping(bytes32 => uint256) public merkleRoots;

    /// @notice Maximum age of a Merkle root (in seconds) before it's considered stale.
    uint256 public constant ROOT_EXPIRY = 1 hours;

    /// @notice Ordered list of recent roots for UI enumeration.
    bytes32[] public rootHistory;

    /// @notice Maximum number of roots kept in history.
    uint256 public constant MAX_ROOT_HISTORY = 100;

    // =========================================================================
    // Modifiers
    // =========================================================================

    modifier onlyAdmin() {
        if (msg.sender != admin) revert ZeroAddress();
        _;
    }

    // =========================================================================
    // Constructor
    // =========================================================================

    /// @param _verifier Address of the deployed Groth16 verifier (from snarkjs export).
    /// @param _admin Address authorized to submit new Merkle roots.
    constructor(address _verifier, address _admin) {
        if (_verifier == address(0) || _admin == address(0)) revert ZeroAddress();
        groth16Verifier = IGroth16Verifier(_verifier);
        admin = _admin;
    }

    // =========================================================================
    // Root management
    // =========================================================================

    /// @notice Submits a new Merkle root from the announcement tree.
    /// @dev Called by the admin/relayer after indexing new announcements.
    function updateMerkleRoot(bytes32 root) external onlyAdmin {
        merkleRoots[root] = block.timestamp;

        if (rootHistory.length >= MAX_ROOT_HISTORY) {
            // Shift: remove oldest by overwriting with last, then pop
            bytes32 oldest = rootHistory[0];
            delete merkleRoots[oldest];
            rootHistory[0] = rootHistory[rootHistory.length - 1];
            rootHistory.pop();
        }
        rootHistory.push(root);

        emit MerkleRootUpdated(root, block.number);
    }

    /// @notice Checks whether a Merkle root is valid and not expired.
    function isRootValid(bytes32 root) public view returns (bool) {
        uint256 ts = merkleRoots[root];
        if (ts == 0) return false;
        return (block.timestamp - ts) <= ROOT_EXPIRY;
    }

    /// @notice Returns the number of roots in history.
    function rootHistoryLength() external view returns (uint256) {
        return rootHistory.length;
    }

    // =========================================================================
    // Proof verification
    // =========================================================================

    /// @notice Proof data structure matching the Groth16 output.
    struct Proof {
        uint256[2] a;
        uint256[2][2] b;
        uint256[2] c;
    }

    /// @notice Verifies a Stealth Attestation ZK-SNARK proof.
    ///
    /// @param proof             The Groth16 proof (a, b, c points).
    /// @param root              The Merkle root used in the proof (must be a recent valid root).
    /// @param attestationId     The attestation/badge ID being proven.
    /// @param externalNullifier Action-scoped nonce (vote ID, loan app, etc.).
    /// @param nullifier         The Sybil-resistant nullifier = Poseidon(stealth_key, external_nullifier).
    ///
    /// @return valid True if the proof is valid and all conditions are met.
    ///
    /// @dev Public signals layout (snarkjs: outputs first, then public inputs in declaration order):
    ///      [0] nullifier           (circuit output)
    ///      [1] is_valid            (circuit output, must be 1)
    ///      [2] merkle_root         (public input)
    ///      [3] attestation_id      (public input)
    ///      [4] external_nullifier  (public input)
    function verifyReputation(
        Proof calldata proof,
        bytes32 root,
        uint256 attestationId,
        uint256 externalNullifier,
        uint256 nullifier
    ) external returns (bool valid) {
        if (usedNullifiers[nullifier]) revert NullifierAlreadyUsed();

        if (!isRootValid(root)) revert InvalidMerkleRoot();

        uint256[5] memory pubSignals;
        pubSignals[0] = nullifier;
        pubSignals[1] = 1;
        pubSignals[2] = uint256(root);
        pubSignals[3] = attestationId;
        pubSignals[4] = externalNullifier;

        bool proofValid = groth16Verifier.verifyProof(
            proof.a,
            proof.b,
            proof.c,
            pubSignals
        );
        if (!proofValid) revert InvalidProof();

        usedNullifiers[nullifier] = true;

        emit ReputationVerified(attestationId, nullifier, msg.sender, root);

        return true;
    }

    /// @notice Read-only verification (does not consume the nullifier).
    function verifyReputationView(
        Proof calldata proof,
        bytes32 root,
        uint256 attestationId,
        uint256 externalNullifier,
        uint256 nullifier
    ) external view returns (bool valid) {
        if (usedNullifiers[nullifier]) return false;
        if (!isRootValid(root)) return false;

        uint256[5] memory pubSignals;
        pubSignals[0] = nullifier;
        pubSignals[1] = 1;
        pubSignals[2] = uint256(root);
        pubSignals[3] = attestationId;
        pubSignals[4] = externalNullifier;

        return groth16Verifier.verifyProof(proof.a, proof.b, proof.c, pubSignals);
    }

    // =========================================================================
    // Admin
    // =========================================================================

    /// @notice Transfers admin role. Use address(0) to renounce.
    function transferAdmin(address newAdmin) external onlyAdmin {
        admin = newAdmin;
    }
}
